---
version: '3.9'

services:
    adminer:
        user: ":" # Without this it fails to write to SQLite DB
        image: adminer:4
        ports:
            - 8080:8080
        environment:
            - ADMINER_DISABLE_INSTANT_LOGIN=false
        volumes:
            - ./server/superdupercloud.db:/var/www/html/superdupercloud.db
            - ./adminer/adminer.css:/var/www/html/adminer.css
            - ./adminer/sqlite-instant-login.php:/var/www/html/plugins-enabled/sqlite-instant-login.php
