---
version: '3.9'

services:
    adminer:
        image: adminer
        ports:
            - 8080:8080
        # environment:
        #     - ADMINER_DEFAULT_SERVER=sqlite3
        volumes:
            - ./server/superdupercloud.db:/var/www/html/superdupercloud.db
            - ./adminer/adminer.css:/var/www/html/adminer.css
