terraform {
  required_version = "~> 1.0.6"

  required_providers {
    sdc = {
      source  = "terraform.kutac.cz/superdupercloud/sdk"
      version = "0.1.0"
    }
  }
}

variable "endpoint" {
  description = "Configuration API Endpoint"
  default     = "http://localhost:8090"
  type        = string
}

variable "api_token" {
  description = "API Token generated by the server"
  type        = string
}
